version: '3'

services:
  permission:
    container_name: "snippet-permission"
    image: ghcr.io/ingsis-group10-2024/snippet-permission-dev:latest
    ports:
      - "8081:8080"
    environment:
      POSTGRES_USER: ${PERMISSION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PERMISSION_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PERMISSION_POSTGRES_DB}
    depends_on:
      - permission-db
    networks:
      - snippet-network

  permission-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${PERMISSION_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PERMISSION_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PERMISSION_POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - permission-db-data:/var/lib/postgresql/data
    networks:
      - snippet-network

  manager:
    container_name: "snippet-manager"
    image: ghcr.io/ingsis-group10-2024/snippet-manager-dev:latest
    ports:
      - "8082:8080"
    environment:
      POSTGRES_USER: ${MANAGER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MANAGER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MANAGER_POSTGRES_DB}
    depends_on:
      - manager-db
    networks:
      - snippet-network

  manager-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${MANAGER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MANAGER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MANAGER_POSTGRES_DB}
    ports:
      - "5434:5432"
    volumes:
      - manager-db-data:/var/lib/postgresql/data
    networks:
      - snippet-network

  runner:
    container_name: "snippet-runner"
    image: ghcr.io/ingsis-group10-2024/snippet-runner-dev:latest
    ports:
      - "8083:8080"
    environment:
      POSTGRES_USER: ${RUNNER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${RUNNER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${RUNNER_POSTGRES_DB}
    depends_on:
      - runner-db
    networks:
      - snippet-network

  runner-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${RUNNER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${RUNNER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${RUNNER_POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - runner-db-data:/var/lib/postgresql/data
    networks:
      - snippet-network

  webserver:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:ro
    networks:
      - snippet-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - snippet-network
 
  printscript-ui:
    image: ghcr.io/ingsis-group10-2024/printscript-ui:latest
    container_name: "printscript-ui"
    ports:
      - "8084:80"
    networks:
      - snippet-network

volumes:
  permission-db-data:
  manager-db-data:
  runner-db-data:

networks:
  snippet-network:
    driver: bridge
