name: "Continuous Deployment to dev"
on:
  push:
    branches:
      - dev
  workflow_dispatch:


jobs:
  update_infra:
    name: Update Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Update and Restart Infrastructure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_URL }}
          username: "mcchicken"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd snippet-infra
            docker compose -f docker-compose.yml stop
            git pull
            docker compose -f docker-compose.yml up -d --build