name: "Continuous Deployment to prod"
on:
  push:
    branches:
      - main

jobs:
  update_infra:
    name: Update Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Update and Restart Infrastructure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_URL }}
          username: "mcchicken"
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          script: |
            cd snippet-infra
            docker compose -f docker-compose.prod.yml stop
            git pull
            docker compose -f docker-compose.prod.yml up -d --build